# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

env:
  - TOX_ENV=py36-flake8
  - TOX_ENV=py36-django-18
  - TOX_ENV=py35-django-18
  - TOX_ENV=py27-django-18
  - TOX_ENV=py36-django-111
  - TOX_ENV=py35-django-111
  - TOX_ENV=py27-django-111
  - TOX_ENV=py36-django-20
  - TOX_ENV=py35-django-20

matrix:
  fast_finish: true

install: pip install -r requirements_test.txt

script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
